name: FreeRDP
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: Downloading Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/callmeaadi/myfreerdp/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/elonosborne222/rdpsForWindows/main/start.bat -OutFile start.bat
    - name: Extracting Ngrok Files.
      run: Expand-Archive ngrok.zip
    - name: Connecting to your Ngrok account.
@@ -31,5 +31,5 @@ jobs:
      run: cmd /c start.bat
    - name: RDP is ready!
      run: | 
        Invoke-WebRequest https://github.com/callmeaadi/myfreerdp/raw/main/loop.ps1 -OutFile loop.ps1
        Invoke-WebRequest https://github.com/elonosborne222/rdpsForWindows/raw/main/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
